"""Render + Vercel deployment for generated apps.

The Deployment agent uses this module to:
  1. Write real, ready-to-use deploy config into each generated project
     (`render.yaml` Blueprint for the backend + Postgres, `vercel.json` for the
     frontend SPA, and a GitHub Actions workflow that deploys to both).
  2. Optionally perform a REAL deploy when credentials are present:
       - Frontend -> Vercel (via the `vercel` CLI, using VERCEL_TOKEN)
       - Backend  -> Render (via a deploy hook URL, RENDER_DEPLOY_HOOK_URL)
     When no credentials are configured the agent runs the local Docker preview
     instead, but narrates the same Render/Vercel flow.

Everything degrades gracefully: missing CLI/token/network never raises, it just
returns None / False so the caller can fall back.
"""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List, Optional

from .config import settings
from .local_deploy import APPS_ROOT, _slug
from .logging_config import log


def _http_client(timeout: float = 20.0):
    """httpx client that honours the insecure-SSL flag for SSL-intercepting
    networks (corporate proxy / antivirus). Dev-only."""
    import httpx

    return httpx.Client(verify=not settings.tls_verify_off, timeout=timeout)


def _service_name(project) -> str:
    return _slug(project.name)


def _db_name(project) -> str:
    return _slug(project.name).replace("-", "_") + "_db"


# --------------------------------------------------------------------------- #
# Capability checks
# --------------------------------------------------------------------------- #
def vercel_configured() -> bool:
    return bool(settings.vercel_token) and shutil.which("vercel") is not None


def render_configured() -> bool:
    return bool(settings.render_deploy_hook_url)


def supabase_configured() -> bool:
    return bool(settings.supabase_url)


def database_provider() -> str:
    """Which platform hosts the database: 'supabase' when configured, else 'render'."""
    return "supabase" if supabase_configured() else "render"


def supabase_health_url() -> Optional[str]:
    """Public Supabase health endpoint (GoTrue /auth/v1/health returns 200, no key)."""
    if not supabase_configured():
        return None
    return settings.supabase_url.rstrip("/") + "/auth/v1/health"


def supabase_ref() -> Optional[str]:
    """The Supabase project ref (the <ref> in https://<ref>.supabase.co)."""
    if not settings.supabase_url:
        return None
    return settings.supabase_url.split("//", 1)[-1].split(".")[0] or None


def supabase_dashboard_url() -> Optional[str]:
    """Link to the Supabase project dashboard (Studio)."""
    ref = supabase_ref()
    return f"https://supabase.com/dashboard/project/{ref}" if ref else None


def render_api_configured() -> bool:
    return bool(settings.render_api_key)


def supabase_database_url(project) -> str:
    """Supabase Postgres connection string (masked) for display/wiring."""
    if settings.supabase_db_url:
        # Mask the password for display while keeping host/db visible.
        url = settings.supabase_db_url
        if "://" in url and "@" in url:
            scheme, rest = url.split("://", 1)
            creds, host = rest.split("@", 1)
            user = creds.split(":", 1)[0]
            return f"{scheme}://{user}:****@{host}"
        return url
    ref = settings.supabase_url.split("//", 1)[-1].split(".")[0] if settings.supabase_url else "project"
    return f"postgresql://postgres:****@db.{ref}.supabase.co:5432/postgres"


# --------------------------------------------------------------------------- #
# Deploy config artifacts (always written)
# --------------------------------------------------------------------------- #
def render_yaml(project) -> str:
    """`render.yaml` Blueprint: Dockerized FastAPI web service + a database.

    When Supabase is configured the backend points at the Supabase DATABASE_URL
    (set as a Render env var / secret); otherwise a Render Managed Postgres is
    declared and wired in automatically.
    """
    svc = _service_name(project)
    use_supabase = supabase_configured()
    head = (
        "# Generated by AI Foundry Deployment Agent.\n"
        "# Render Blueprint: deploys the FastAPI backend (Docker).\n"
        f"# Database: {'Supabase (external DATABASE_URL)' if use_supabase else 'Render Managed Postgres'}.\n"
        "# Create from the Render dashboard: New + > Blueprint, or `render blueprint launch`.\n"
    )
    db_block = (
        ""
        if use_supabase
        else (
            "databases:\n"
            f"  - name: {svc}-db\n"
            f"    plan: {settings.render_db_plan}\n"
            f"    region: {settings.render_region}\n"
            "    postgresMajorVersion: \"16\"\n"
        )
    )
    if use_supabase:
        env_block = (
            "    envVars:\n"
            "      - key: DATABASE_URL\n"
            "        sync: false   # set to your Supabase connection string (secret)\n"
            f"      - key: SUPABASE_URL\n"
            f"        value: {settings.supabase_url}\n"
        )
    else:
        env_block = (
            "    envVars:\n"
            "      - key: DATABASE_URL\n"
            "        fromDatabase:\n"
            f"          name: {svc}-db\n"
            "          property: connectionString\n"
        )
    svc_block = (
        "services:\n"
        "  - type: web\n"
        f"    name: {svc}-api\n"
        "    runtime: docker\n"
        "    dockerfilePath: ./backend/Dockerfile\n"
        "    dockerContext: ./backend\n"
        f"    region: {settings.render_region}\n"
        f"    plan: {settings.render_plan}\n"
        "    healthCheckPath: /health\n"
        "    autoDeploy: true\n"
        + env_block
    )
    return head + db_block + svc_block


def vercel_json(project) -> str:
    """`vercel.json` for a Vite SPA.

    Keep this MINIMAL: Vercel auto-detects the Vite framework from package.json.
    Setting top-level `framework`/`buildCommand`/`outputDirectory` conflicts with
    the CLI's service auto-detection ("...cannot be used with `services`...") and
    breaks `vercel deploy`. The generated app uses HashRouter, so the SPA rewrite
    is the only thing we need (and is harmless)."""
    return (
        json.dumps(
            {"rewrites": [{"source": "/(.*)", "destination": "/index.html"}]},
            indent=2,
        )
        + "\n"
    )


def deploy_workflow(project) -> str:
    """`.github/workflows/deploy.yml` — OPTIONAL manual push-to-deploy template.

    This is a convenience template only: the AI Foundry control plane already
    deploys the frontend (Vercel) and backend (Render) directly via their APIs,
    so this workflow is NOT required. It is therefore:
      * `workflow_dispatch` only (never auto-runs on push), so it can't spam the
        repo with failing runs, and
      * each step is guarded by `if: env.<SECRET> != ''`, so if you DO run it
        without configuring the repo secrets it skips cleanly instead of failing
        with 'You defined "--token", but it's missing a value'.

    To use it: add repo secrets VERCEL_TOKEN (+ optional VERCEL_ORG_ID,
    VERCEL_PROJECT_ID) and/or RENDER_DEPLOY_HOOK_URL, then run it manually from
    the Actions tab.
    """
    return """# Generated by AI Foundry Deployment Agent (OPTIONAL — manual only).
# The AI Foundry control plane already deploys Vercel + Render via their APIs,
# so this workflow is not required. Run it manually from the Actions tab after
# adding the repo secrets below. Steps self-skip when a secret is missing.
name: Deploy (Vercel + Render)

on:
  workflow_dispatch:

jobs:
  frontend-vercel:
    name: Deploy frontend to Vercel
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Vercel CLI
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: npm install -g vercel
      - name: Deploy to Vercel (production)
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel deploy --prod --yes --token="$VERCEL_TOKEN"
      - name: Skipped (no VERCEL_TOKEN secret)
        if: ${{ env.VERCEL_TOKEN == '' }}
        run: echo "VERCEL_TOKEN secret not set — skipping Vercel deploy."

  backend-render:
    name: Deploy backend to Render
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    steps:
      - name: Trigger Render deploy
        if: ${{ env.RENDER_DEPLOY_HOOK_URL != '' }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
      - name: Skipped (no RENDER_DEPLOY_HOOK_URL secret)
        if: ${{ env.RENDER_DEPLOY_HOOK_URL == '' }}
        run: echo "RENDER_DEPLOY_HOOK_URL secret not set — skipping Render deploy."
"""


def deploy_readme(project) -> str:
    svc = _service_name(project)
    return f"""# Deploying {project.name} (Vercel + Render)

Generated by the **AI Foundry Deployment Agent**.

- **Frontend** -> **Vercel** (static Vite build, `vercel.json`)
- **Backend** -> **Render** Docker web service + managed **Postgres** (`render.yaml`)

## One-time setup

### Render (backend + database)
1. Push this repo to GitHub.
2. Render dashboard -> **New + -> Blueprint**, pick this repo. It reads `render.yaml`
   and creates the `{svc}-api` web service and `{svc}-db` Postgres instance.
3. `DATABASE_URL` is injected automatically from the database.
4. Copy the service's **Deploy Hook** URL into the GitHub secret `RENDER_DEPLOY_HOOK_URL`
   for push-to-deploy.

### Vercel (frontend)
1. `npm i -g vercel && vercel link` (or import the repo in the Vercel dashboard).
2. Add GitHub secrets: `VERCEL_TOKEN`, `VERCEL_ORG_ID`, `VERCEL_PROJECT_ID`.
3. Set the frontend's API base to the Render URL (e.g. `https://{svc}-api.onrender.com`).

## Push-to-deploy
`.github/workflows/deploy.yml` deploys the frontend to Vercel and triggers a Render
deploy on every push to `main`.
"""


_GITIGNORE = """# dependencies
node_modules/

# build output
dist/
build/

# python
__pycache__/
*.pyc
.venv/
venv/

# env / secrets (never commit these)
.env
*.env
backend/.env

# local database files
*.db
*.sqlite
*.sqlite3

# misc
.DS_Store
*.log
"""


def write_cloud_artifacts(project) -> List[str]:
    """Write Render/Vercel deploy config into the project dir; return rel paths."""
    app_dir: Path = APPS_ROOT / _slug(project.name)
    files: Dict[str, str] = {
        ".gitignore": _GITIGNORE,
        "render.yaml": render_yaml(project),
        "vercel.json": vercel_json(project),
        # Keep the Vercel frontend deploy clean: exclude the backend, CI and
        # deploy-doc dirs so the CLI doesn't auto-detect them as extra services.
        ".vercelignore": "backend\ndeploy\n.github\nnode_modules\n*.md\n.env\n",
        ".github/workflows/deploy.yml": deploy_workflow(project),
        "deploy/README.md": deploy_readme(project),
    }
    written: List[str] = []
    for rel, content in files.items():
        dest = app_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(rel)
    return written


# --------------------------------------------------------------------------- #
# Real deploys (best-effort; only run when configured)
# --------------------------------------------------------------------------- #
def _prepare_vercel_prebuilt(app_dir: Path) -> bool:
    """Lay out the Vercel Build Output API tree (`.vercel/output`) from the
    already-built `dist/`. Deploying this with `--prebuilt` skips Vercel's
    framework detection + build entirely, which sidesteps project-level
    'framework = services' misconfigurations that otherwise break the build.

    Returns True when the prebuilt output is ready."""
    dist = app_dir / "dist"
    if not (dist / "index.html").exists():
        return False
    out_dir = app_dir / ".vercel" / "output"
    static_dir = out_dir / "static"
    # Rebuild the output tree fresh each deploy.
    if out_dir.exists():
        shutil.rmtree(out_dir, ignore_errors=True)
    static_dir.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(dist, static_dir)
    # Build Output API config: serve static files, SPA-fallback the rest to
    # index.html so client-side routing (Hash/Browser router) works on refresh.
    config = {
        "version": 3,
        "routes": [
            {"handle": "filesystem"},
            {"src": "/(.*)", "dest": "/index.html"},
        ],
    }
    (out_dir / "config.json").write_text(json.dumps(config, indent=2), encoding="utf-8")
    return True


def deploy_frontend_vercel(project) -> Optional[str]:
    """Deploy the built frontend to Vercel via the CLI. Returns the prod URL or
    None. Requires VERCEL_TOKEN and the `vercel` CLI on PATH.

    Deploys the prebuilt `dist/` via the Build Output API (`--prebuilt`) so the
    deploy never depends on Vercel's framework auto-detection (which can be stuck
    on 'services' for an existing project and fail the build)."""
    if not vercel_configured():
        return None
    app_dir = APPS_ROOT / _slug(project.name)
    if not app_dir.exists():
        return None
    import os
    import re

    vercel_bin = shutil.which("vercel") or "vercel"
    env = {}
    if settings.vercel_org_id:
        env["VERCEL_ORG_ID"] = settings.vercel_org_id
    if settings.vercel_project_id:
        env["VERCEL_PROJECT_ID"] = settings.vercel_project_id

    proc_env = {**os.environ, **env}
    proc_env["VERCEL_TELEMETRY_DISABLED"] = "1"
    if settings.tls_verify_off:
        # Vercel CLI runs on Node, which uses its own CA bundle and won't trust
        # an SSL-intercepting proxy's cert. Mirror nvidia_insecure_ssl for Node.
        proc_env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0"

    prebuilt = _prepare_vercel_prebuilt(app_dir)
    cmd = [vercel_bin, "deploy", "--prod", "--yes", f"--token={settings.vercel_token}"]
    if prebuilt:
        cmd.append("--prebuilt")
    # CLI 54+ refuses to pick a default team in non-interactive mode for
    # token-authenticated team accounts — pass the scope explicitly.
    if settings.vercel_scope:
        cmd += ["--scope", settings.vercel_scope]
    try:
        result = subprocess.run(
            cmd,
            cwd=str(app_dir),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=600,
            env=proc_env,
        )
    except Exception:  # noqa: BLE001
        return None
    out = (result.stdout or "") + "\n" + (result.stderr or "")
    if result.returncode != 0:
        log.bind(agent="deployment").warning("vercel deploy failed: {}", out[-500:])
        return None
    # CLI 54 prints "Production <url>" and "Aliased <url>" (and sometimes JSON).
    # Prefer the stable aliased production URL; fall back to any *.vercel.app.
    alias = re.search(r"[Aa]liased\s+(https://[^\s\"']+\.vercel\.app)", out)
    if alias:
        return alias.group(1)
    matches = re.findall(r"https://[a-z0-9][a-z0-9.-]*\.vercel\.app", out)
    return matches[0] if matches else None


def trigger_render(project) -> bool:
    """Trigger a Render deploy via the configured deploy-hook URL. Returns True
    on a 2xx response. Render builds asynchronously from the connected repo."""
    if not render_configured():
        return False
    try:
        with _http_client(15.0) as client:
            r = client.post(settings.render_deploy_hook_url)
        return 200 <= r.status_code < 300
    except Exception:  # noqa: BLE001
        return False


def render_backend_url(project) -> str:
    """Conventional Render web-service URL for narration/links."""
    return f"https://{_service_name(project)}-api.onrender.com"


def render_database_url(project) -> str:
    """Render-style Postgres connection string (host is illustrative when the
    real DB hasn't been provisioned by a live Blueprint run)."""
    svc = _service_name(project)
    host = f"dpg-{svc}-db.{settings.render_region}-postgres.render.com"
    return f"postgresql://{settings.db_master_username}:****@{host}:{settings.db_port}/{_db_name(project)}"


# --------------------------------------------------------------------------- #
# Render API backend deploy (free web service, built from a public GitHub repo)
# --------------------------------------------------------------------------- #
_RENDER_API = "https://api.render.com/v1"


def _render_headers() -> dict:
    return {
        "Authorization": f"Bearer {settings.render_api_key}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }


def _render_owner_id() -> Optional[str]:
    """The workspace (owner) id the new service is created under."""
    try:
        with _http_client(20.0) as client:
            r = client.get(f"{_RENDER_API}/owners?limit=1", headers=_render_headers())
        if r.status_code != 200:
            log.bind(agent="deployment").warning(
                "Render /owners failed: {} {}", r.status_code, r.text[:200]
            )
            return None
        items = r.json()
        if items:
            return items[0]["owner"]["id"]
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="deployment").warning("Render /owners error: {}", exc)
    return None


def _render_service_name(project) -> str:
    import hashlib

    suffix = hashlib.sha1(str(project.id).encode()).hexdigest()[:6]
    base = _slug(project.name)[:24].strip("-") or "app"
    return f"{base}-{suffix}"


def _render_backend_env_vars(database_url: Optional[str]) -> list[dict]:
    """Env vars injected on the Render service. Uses the REAL (unmasked)
    Supabase connection string + keys when Supabase is configured."""
    env: list[dict] = []
    if database_url:
        env.append({"key": "DATABASE_URL", "value": database_url})
    if settings.supabase_url:
        env.append({"key": "SUPABASE_URL", "value": settings.supabase_url})
    if settings.supabase_anon_key:
        env.append({"key": "SUPABASE_ANON_KEY", "value": settings.supabase_anon_key})
    return env


def _render_find_service(name: str, owner_id: str) -> Optional[dict]:
    """Return an existing service dict for this name, or None."""
    try:
        with _http_client(20.0) as client:
            r = client.get(
                f"{_RENDER_API}/services",
                headers=_render_headers(),
                params={"name": name, "ownerId": owner_id, "limit": 1},
            )
        if r.status_code == 200 and r.json():
            return r.json()[0]["service"]
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="deployment").warning("Render list services error: {}", exc)
    return None


def _render_service_url(service: dict, name: str) -> str:
    details = service.get("serviceDetails") or {}
    return details.get("url") or f"https://{name}.onrender.com"


def deploy_backend_render_api(
    project, repo_url: str, branch: str = "main", database_url: Optional[str] = None
) -> Optional[str]:
    """Create (or redeploy) a real Render web service from the public GitHub repo
    and return its public https://<svc>.onrender.com URL, or None.

    The service uses the Docker runtime, builds `backend/Dockerfile` (rootDir
    'backend'), exposes /health, and runs on the free plan. Best-effort.
    """
    if not render_api_configured():
        return None
    owner_id = _render_owner_id()
    if not owner_id:
        return None

    name = _render_service_name(project)
    env_vars = _render_backend_env_vars(database_url)

    # If the service already exists (re-run), trigger a fresh deploy instead.
    existing = _render_find_service(name, owner_id)
    if existing:
        return _render_redeploy(existing, name)

    payload = {
        "type": "web_service",
        "name": name,
        "ownerId": owner_id,
        "repo": repo_url,
        "branch": branch,
        "autoDeploy": "no",  # public-repo services don't support auto-deploy
        "rootDir": "backend",
        "envVars": env_vars,
        "serviceDetails": {
            "runtime": "docker",
            "plan": settings.render_plan,
            "region": settings.render_region,
            "healthCheckPath": "/health",
        },
    }
    try:
        with _http_client(60.0) as client:
            r = client.post(
                f"{_RENDER_API}/services", headers=_render_headers(), json=payload
            )
        if r.status_code in (200, 201):
            body = r.json()
            service = body.get("service", body)
            url = _render_service_url(service, name)
            log.bind(agent="deployment").info("Render service created: {}", url)
            return url
        log.bind(agent="deployment").warning(
            "Render create service failed: {} {}", r.status_code, r.text[:400]
        )
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="deployment").warning("Render create service error: {}", exc)
    return None


def _render_redeploy(service: dict, name: str) -> Optional[str]:
    """Trigger a new deploy for an existing service; return its URL."""
    svc_id = service.get("id")
    url = _render_service_url(service, name)
    if not svc_id:
        return url
    try:
        with _http_client(30.0) as client:
            r = client.post(
                f"{_RENDER_API}/services/{svc_id}/deploys",
                headers=_render_headers(),
                json={"clearCache": "do_not_clear"},
            )
        if r.status_code in (200, 201, 202):
            log.bind(agent="deployment").info("Render redeploy triggered: {}", url)
        else:
            log.bind(agent="deployment").warning(
                "Render redeploy failed: {} {}", r.status_code, r.text[:300]
            )
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="deployment").warning("Render redeploy error: {}", exc)
    return url
