"""Real local Docker Compose deployment for generated apps.

Builds and runs each generated app as containers:

    frontend  -> nginx serving the Vite production build (dist/)
    backend   -> uvicorn running the generated FastAPI app (sqlite/in-memory)

`up()` brings the stack up with real `docker compose up -d --build`, on free host
ports, with the backend URL injected into the frontend as window.API_BASE. The
self-healing demo maps to real container ops: `kill()` stops the stack (service
down) and `restart()` brings it back.

Everything is best-effort: callers should fall back to the lightweight local
runtime (local_deploy) if Docker isn't available or a build fails.
"""
from __future__ import annotations

import json
import shutil
import socket
import subprocess
import time
import urllib.request
from pathlib import Path
from typing import Dict, List, Optional

from .config import settings
from .local_deploy import APPS_ROOT, _free_port, _inject_api_base, _slug
from .logging_config import log

_DOCKER = shutil.which("docker") or "docker"

# project_id -> {"slug": str, "dir": Path, "frontend_port": int, "backend_port": int}
_RUNNING_DOCKER: Dict[str, Dict] = {}


def _host() -> str:
    """The host to put in the deployed app's URLs. Defaults to this machine's
    LAN IP so the links are reachable from other devices on the network."""
    if settings.public_host:
        return settings.public_host
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # No packets are sent; this just picks the outbound interface's IP.
        s.connect(("8.8.8.8", 80))
        return s.getsockname()[0]
    except Exception:  # noqa: BLE001
        return "localhost"
    finally:
        s.close()


def docker_available() -> bool:
    """True if the docker CLI is present and the daemon is reachable."""
    if not shutil.which("docker"):
        return False
    try:
        r = subprocess.run(
            [_DOCKER, "info", "--format", "{{.ServerVersion}}"],
            capture_output=True, text=True, timeout=15, shell=False,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


# --- artifact generation -------------------------------------------------------

def _frontend_dockerfile() -> str:
    return (
        "# Generated by AI Foundry — serves the Vite production build via nginx.\n"
        "FROM nginx:alpine\n"
        "COPY dist/ /usr/share/nginx/html/\n"
        "COPY nginx.conf /etc/nginx/conf.d/default.conf\n"
        "EXPOSE 80\n"
    )


def _frontend_nginx_conf() -> str:
    # SPA fallback: route every unknown path back to index.html so client-side
    # routers (BrowserRouter AND HashRouter) work on refresh / direct links.
    return (
        "server {\n"
        "  listen 80;\n"
        "  root /usr/share/nginx/html;\n"
        "  index index.html;\n"
        "  location / { try_files $uri $uri/ /index.html; }\n"
        "}\n"
    )


def _backend_dockerfile() -> str:
    # Shell-form CMD so $PORT (injected by Render) is honored; defaults to 8000
    # for local Docker Compose (which uses the fixed internal port).
    return (
        "FROM python:3.13-slim\n"
        "WORKDIR /app\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "COPY . .\n"
        "EXPOSE 8000\n"
        'CMD uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}\n'
    )


def _db_name(project) -> str:
    return _slug(project.name).replace("-", "_") + "_db"


def _compose_yaml(project) -> str:
    slug = _slug(project.name)
    db_name = _db_name(project)
    db_user = settings.db_master_username
    db_pass = "app_secret"  # dev-only; real deploys would inject via secrets
    # Backend health uses stdlib (no curl in slim image). Ports come from .env.
    health_py = (
        "import urllib.request,sys;"
        "sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health').status==200 else 1)"
    )
    return (
        "services:\n"
        "  db:\n"
        "    image: postgres:16-alpine\n"
        "    environment:\n"
        f"      POSTGRES_USER: {db_user}\n"
        f"      POSTGRES_PASSWORD: {db_pass}\n"
        f"      POSTGRES_DB: {db_name}\n"
        "    volumes:\n"
        "      - dbdata:/var/lib/postgresql/data\n"
        "    ports:\n"
        '      - "${DB_PORT}:5432"\n'
        "    restart: unless-stopped\n"
        "    healthcheck:\n"
        f'      test: ["CMD-SHELL", "pg_isready -U {db_user} -d {db_name}"]\n'
        "      interval: 10s\n"
        "      timeout: 5s\n"
        "      retries: 5\n"
        "  backend:\n"
        "    build:\n"
        "      context: ./backend\n"
        f"    image: {slug}-backend\n"
        "    environment:\n"
        f"      DATABASE_URL: postgresql://{db_user}:{db_pass}@db:5432/{db_name}\n"
        "    depends_on:\n"
        "      db:\n"
        "        condition: service_healthy\n"
        "    ports:\n"
        '      - "${BACKEND_PORT}:8000"\n'
        "    restart: unless-stopped\n"
        "    healthcheck:\n"
        f'      test: ["CMD", "python", "-c", "{health_py}"]\n'
        "      interval: 10s\n"
        "      timeout: 5s\n"
        "      retries: 5\n"
        "      start_period: 10s\n"
        "  frontend:\n"
        "    build:\n"
        "      context: .\n"
        "      dockerfile: frontend.Dockerfile\n"
        f"    image: {slug}-frontend\n"
        "    ports:\n"
        '      - "${FRONTEND_PORT}:80"\n'
        "    depends_on:\n"
        "      - backend\n"
        "    restart: unless-stopped\n"
        "volumes:\n"
        "  dbdata:\n"
    )


_ROOT_DOCKERIGNORE = (
    "node_modules\n.git\n.github\nbackend\nsrc\ndeploy\n*.md\n.env\n"
)


def write_docker_artifacts(project) -> List[str]:
    """Write the runnable full-stack Docker artifacts; return relative paths."""
    app_dir = APPS_ROOT / _slug(project.name)
    files = {
        "docker-compose.yml": _compose_yaml(project),
        "frontend.Dockerfile": _frontend_dockerfile(),
        "nginx.conf": _frontend_nginx_conf(),
        ".dockerignore": _ROOT_DOCKERIGNORE,
        "backend/Dockerfile": _backend_dockerfile(),
        "backend/.dockerignore": "__pycache__/\n*.pyc\n.env\n.venv/\nnode_modules/\n",
    }
    written: List[str] = []
    for rel, content in files.items():
        dest = app_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(rel)
    return written


# --- runtime -------------------------------------------------------------------

def _compose(app_dir: Path, slug: str, *args: str, timeout: int = 120) -> subprocess.CompletedProcess:
    return subprocess.run(
        [_DOCKER, "compose", "-p", slug, *args],
        cwd=str(app_dir),
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=timeout, shell=False,
    )


def _ensure_dist(app_dir: Path) -> None:
    """Guarantee a dist/ exists for the frontend image (build output, or the
    static fallback index.html promoted into dist/)."""
    dist = app_dir / "dist"
    if (dist / "index.html").exists():
        return
    dist.mkdir(parents=True, exist_ok=True)
    index = app_dir / "index.html"
    if index.exists():
        (dist / "index.html").write_text(index.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")
    else:
        (dist / "index.html").write_text("<!doctype html><title>App</title><h1>App</h1>", encoding="utf-8")


def _wait_http(url: str, timeout: int = 40) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as r:
                if r.status == 200:
                    return True
        except Exception:  # noqa: BLE001
            time.sleep(1.0)
    return False


def up(project) -> Optional[Dict[str, str]]:
    """Build and run the app's containers. Returns {frontend_url, backend_url}
    on success, or None on failure (caller should fall back)."""
    if not docker_available():
        log.bind(agent="deployment").warning("docker unavailable; cannot deploy via compose")
        return None

    slug = _slug(project.name)
    app_dir = APPS_ROOT / slug
    if not app_dir.exists():
        return None

    # Clear any previous stack AND its named volumes. Without removing the
    # `dbdata` volume, a stale Postgres data dir from an earlier run is reused
    # and the configured POSTGRES_DB is never created (Postgres only initializes
    # it on a fresh volume) -> backend crash-loops with 'database ... does not
    # exist'. A fresh volume guarantees the DB is created on this deploy.
    if (app_dir / "docker-compose.yml").exists():
        try:
            _compose(app_dir, slug, "down", "-v", timeout=120)
        except Exception:  # noqa: BLE001
            pass
    _RUNNING_DOCKER.pop(project.id, None)

    _ensure_dist(app_dir)
    host = _host()
    frontend_port = _free_port()
    backend_port = _free_port()
    db_port = _free_port()

    # Point the browser frontend at the live backend (permissive CORS on backend).
    # Uses the LAN IP so the page works when opened from another device.
    _inject_api_base(app_dir / "dist", f"http://{host}:{backend_port}")

    write_docker_artifacts(project)
    (app_dir / ".env").write_text(
        f"FRONTEND_PORT={frontend_port}\nBACKEND_PORT={backend_port}\nDB_PORT={db_port}\n",
        encoding="utf-8",
    )

    try:
        result = _compose(app_dir, slug, "up", "-d", "--build", timeout=settings.docker_build_timeout_s)
    except subprocess.TimeoutExpired:
        log.bind(agent="deployment").warning("docker compose up timed out")
        return None
    if result.returncode != 0:
        tail = (result.stdout or "")[-1200:]
        log.bind(agent="deployment").warning("docker compose up failed: {}", tail)
        return None

    frontend_url = f"http://{host}:{frontend_port}/"
    backend_url = f"http://{host}:{backend_port}/"
    _RUNNING_DOCKER[project.id] = {
        "slug": slug, "dir": app_dir, "host": host,
        "frontend_port": frontend_port, "backend_port": backend_port, "db_port": db_port,
    }
    # Health-check via localhost (we're on the host); ports are published to 0.0.0.0.
    _wait_http(f"http://localhost:{backend_port}/health", timeout=40)
    _wait_http(f"http://localhost:{frontend_port}/", timeout=20)
    db_name = _db_name(project)
    database_url = f"postgresql://{settings.db_master_username}:****@{host}:{db_port}/{db_name}"
    log.bind(agent="deployment").info(
        "docker stack up: frontend={} backend={} db={}:{}", frontend_url, backend_url, host, db_port
    )
    return {"frontend_url": frontend_url, "backend_url": backend_url, "database_url": database_url}


def current_urls(project) -> Optional[Dict[str, str]]:
    entry = _RUNNING_DOCKER.get(project.id)
    if not entry:
        return None
    host = entry.get("host", "localhost")
    return {
        "frontend_url": f"http://{host}:{entry['frontend_port']}/",
        "backend_url": f"http://{host}:{entry['backend_port']}/",
    }


def kill(project) -> None:
    """Stop the running stack (simulated service outage for the heal demo)."""
    entry = _RUNNING_DOCKER.get(project.id)
    if not entry:
        return
    try:
        _compose(entry["dir"], entry["slug"], "stop", timeout=60)
        log.bind(agent="monitoring").warning("docker stack stopped (incident): {}", entry["slug"])
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="monitoring").warning("docker stop failed: {}", exc)


def restart(project) -> Optional[str]:
    """Bring a stopped stack back up (self-healing). Returns frontend URL.

    A plain restart only recovers transient outages. If the backend does NOT
    reach health after the restart (e.g. crash-loop from a missing database or
    a bad image), we escalate to a full rebuild via `up()` — which clears the
    stale volume and rebuilds the image, picking up the resilient db layer."""
    entry = _RUNNING_DOCKER.get(project.id)
    if not entry:
        # Nothing tracked — do a full up.
        urls = up(project)
        return urls["frontend_url"] if urls else None
    try:
        _compose(entry["dir"], entry["slug"], "up", "-d", timeout=120)
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="healing").warning("docker restart failed: {}", exc)
        return None
    host = entry.get("host", "localhost")
    frontend_url = f"http://{host}:{entry['frontend_port']}/"
    healthy = _wait_http(f"http://localhost:{entry['backend_port']}/health", timeout=40)
    if not healthy:
        # Restart didn't fix it — the container is crash-looping. Escalate to a
        # clean rebuild (fresh DB volume + rebuilt image) so the fix lands.
        log.bind(agent="healing").warning(
            "docker restart did not reach health; escalating to full rebuild: {}", entry["slug"]
        )
        urls = up(project)
        return urls["frontend_url"] if urls else frontend_url
    log.bind(agent="healing").info("docker stack restarted: {}", frontend_url)
    return frontend_url


def down(project) -> None:
    """Tear down the stack and remove containers."""
    slug = _slug(project.name)
    app_dir = APPS_ROOT / slug
    if not (app_dir / "docker-compose.yml").exists():
        _RUNNING_DOCKER.pop(project.id, None)
        return
    try:
        _compose(app_dir, slug, "down", timeout=120)
    except Exception:  # noqa: BLE001
        pass
    _RUNNING_DOCKER.pop(project.id, None)
