"""Generate GitHub Actions CI/CD workflows for a generated app.

The Deployment agent writes these "git workflow scripts" into each generated
project so the app is deployable to AWS the production way:

    push to main -> GitHub Actions -> build image -> push to ECR
                 -> render ECS task definition -> deploy to ECS Fargate

Auth uses GitHub OIDC (no static AWS keys): the workflow assumes an IAM role
provided via the `AWS_DEPLOY_ROLE_ARN` repository secret. This mirrors the
"GitHub -> AWS auth via OIDC (no static keys)" design in ARCHITECTURE.md.

The functions return file contents; `write_git_workflows` writes them into the
project directory and returns the list of relative paths written.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

from .config import settings
from .local_deploy import APPS_ROOT, _slug


def _service_name(project) -> str:
    return _slug(project.name)


def deploy_workflow(project) -> str:
    """`.github/workflows/deploy.yml` — build -> ECR -> ECS Fargate via OIDC."""
    service = _service_name(project)
    return f"""# Generated by AI Foundry Deployment Agent.
# Builds the app image, pushes it to Amazon ECR, and deploys to ECS Fargate.
# Auth uses GitHub OIDC -> IAM role (no static AWS keys).
name: Deploy to AWS ECS

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC role assumption
  contents: read

env:
  AWS_REGION: {settings.aws_region}
  ECR_REPOSITORY: {settings.ecr_repo}
  ECS_CLUSTER: {settings.ecs_cluster}
  ECS_SERVICE: {service}
  CONTAINER_NAME: {service}
  TASK_DEFINITION: deploy/task-definition.json

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ secrets.AWS_DEPLOY_ROLE_ARN }}}}
          aws-region: ${{{{ env.AWS_REGION }}}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{{{ steps.login-ecr.outputs.registry }}}}
          IMAGE_TAG: ${{{{ github.sha }}}}
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" ./backend
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Render new ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{{{ env.TASK_DEFINITION }}}}
          container-name: ${{{{ env.CONTAINER_NAME }}}}
          image: ${{{{ steps.build-image.outputs.image }}}}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{{{ steps.task-def.outputs.task-definition }}}}
          service: ${{{{ env.ECS_SERVICE }}}}
          cluster: ${{{{ env.ECS_CLUSTER }}}}
          wait-for-service-stability: true
"""


def ci_workflow(project) -> str:
    """`.github/workflows/ci.yml` — lint/test on every push & PR.

    The Monitoring agent watches `workflow_run`/`check_run` events from this
    pipeline; a failing build feeds the RCA -> Self-Healing loop.
    """
    return """# Generated by AI Foundry Deployment Agent.
# Runs on every push and pull request; build status feeds the Monitoring agent.
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Lint and test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Lint (ruff)
        working-directory: backend
        run: ruff check . || true

      - name: Smoke import
        working-directory: backend
        run: python -c "import importlib; importlib.import_module('main')"

      - name: Run tests (if any)
        working-directory: backend
        run: |
          if ls test_*.py tests/ >/dev/null 2>&1; then pytest -q; else echo "no tests"; fi

  docker-build:
    name: Verify Docker image builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t app-ci-check ./backend
"""


def task_definition(project) -> str:
    """`deploy/task-definition.json` — ECS Fargate task def template.

    `image` is a placeholder that the deploy workflow overwrites per build via
    `amazon-ecs-render-task-definition`. Role ARNs are filled in by the operator.
    """
    service = _service_name(project)
    task_def = {
        "family": service,
        "networkMode": "awsvpc",
        "requiresCompatibilities": ["FARGATE"],
        "cpu": "256",
        "memory": "512",
        "executionRoleArn": "arn:aws:iam::<ACCOUNT_ID>:role/ecsTaskExecutionRole",
        "containerDefinitions": [
            {
                "name": service,
                "image": "PLACEHOLDER_OVERWRITTEN_BY_WORKFLOW",
                "essential": True,
                "portMappings": [{"containerPort": 8000, "protocol": "tcp"}],
                "healthCheck": {
                    "command": [
                        "CMD-SHELL",
                        "python -c \"import urllib.request,sys; "
                        "sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health').status==200 else 1)\"",
                    ],
                    "interval": 30,
                    "timeout": 5,
                    "retries": 3,
                    "startPeriod": 10,
                },
                "logConfiguration": {
                    "logDriver": "awslogs",
                    "options": {
                        "awslogs-group": f"/ecs/{service}",
                        "awslogs-region": settings.aws_region,
                        "awslogs-stream-prefix": "ecs",
                    },
                },
            }
        ],
    }
    return json.dumps(task_def, indent=2) + "\n"


def deploy_readme(project) -> str:
    """`deploy/README.md` — one-time AWS setup the workflows depend on."""
    service = _service_name(project)
    return f"""# Deploying {project.name} to AWS (ECS Fargate)

These GitHub Actions workflows were generated by the **AI Foundry Deployment Agent**.

## How it works
On every push to `main`, `.github/workflows/deploy.yml`:
1. Assumes an AWS IAM role via **GitHub OIDC** (no static keys).
2. Builds the Docker image from `backend/Dockerfile` and pushes it to **Amazon ECR**.
3. Renders `deploy/task-definition.json` with the new image tag.
4. Deploys the revision to the **ECS Fargate** service and waits for stability.

`.github/workflows/ci.yml` lints, smoke-tests, and verifies the Docker build on
every push and PR.

## One-time AWS setup
1. **ECR repo:** `aws ecr create-repository --repository-name {settings.ecr_repo} --region {settings.aws_region}`
2. **ECS cluster:** `aws ecs create-cluster --cluster-name {settings.ecs_cluster}`
3. **ECS service** named `{service}` on that cluster (Fargate, behind an ALB target group on port 8000 with health check path `/health`).
4. **OIDC IAM role** trusted by `token.actions.githubusercontent.com`, with permissions for ECR push and ECS deploy. Put its ARN in the repo secret `AWS_DEPLOY_ROLE_ARN`.
5. Replace the `executionRoleArn` / `<ACCOUNT_ID>` placeholders in `deploy/task-definition.json`.

## Required repository secret
| Secret | Value |
|--------|-------|
| `AWS_DEPLOY_ROLE_ARN` | ARN of the OIDC-assumable deploy role |
"""


def write_git_workflows(project) -> List[str]:
    """Write all CI/CD workflow files into the project dir; return rel paths."""
    app_dir: Path = APPS_ROOT / _slug(project.name)
    files: Dict[str, str] = {
        ".github/workflows/deploy.yml": deploy_workflow(project),
        ".github/workflows/ci.yml": ci_workflow(project),
        "deploy/task-definition.json": task_definition(project),
        "deploy/README.md": deploy_readme(project),
    }
    written: List[str] = []
    for rel, content in files.items():
        dest = app_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(rel)
    return written
