"""Real local deployment for generated apps.

The Developer agent writes a self-contained `index.html` for the project, and the
Deployment agent serves it on a free local port via a child `http.server` process.
This makes `deploy_url` a real, openable URL. The same start/stop hooks power the
self-healing demo: killing the service really stops the process; healing restarts it.

Phase 2 (AWS ECS/Fargate via boto3) can replace `start`/`stop` without touching
the agents that call them.
"""
from __future__ import annotations

import html
import json
import re
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, Optional

from .logging_config import log

_NPM = shutil.which("npm") or shutil.which("npm.cmd") or "npm.cmd"

APPS_ROOT = Path(__file__).resolve().parent.parent / "generated_apps"

# project_id -> {"port": int, "proc": Popen, "dir": Path}
_RUNNING: Dict[str, Dict[str, Any]] = {}
# project_id -> {"port": int, "proc": Popen, "dir": Path} for the live FastAPI backend
_RUNNING_API: Dict[str, Dict[str, Any]] = {}


def _slug(name: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in name.lower()).strip("-") or "app"


def _free_port() -> int:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def _as_text(value: Any) -> str:
    """Architecture values may be plain strings or nested dicts; render either."""
    if isinstance(value, dict):
        tech = value.get("technology") or value.get("tech") or ""
        feats = value.get("features")
        if isinstance(feats, list) and feats:
            return f"{tech} — " + "; ".join(str(f) for f in feats[:4]) if tech else "; ".join(str(f) for f in feats[:4])
        return str(tech) if tech else ", ".join(f"{k}: {v}" for k, v in value.items())
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value) if value is not None else "—"


def build_app(project, page_html: Optional[str] = None) -> Path:
    """Write the generated app's index.html and return its directory.

    If `page_html` is provided (e.g. generated by Nemotron) it is used as-is;
    otherwise a functional interactive fallback SPA is rendered.
    """
    app_dir = APPS_ROOT / _slug(project.name)
    app_dir.mkdir(parents=True, exist_ok=True)
    page = page_html if (page_html and "<" in page_html) else working_app_html(project)
    (app_dir / "index.html").write_text(page, encoding="utf-8")
    return app_dir


def write_files(project, files: Dict[str, str], ensure_index: bool = True) -> Path:
    """Write a multi-file generated project to disk and return its directory.

    `files` maps relative path -> content. When `ensure_index` is True, guarantees
    a working `index.html` exists at the root (so the served app always opens),
    falling back to the interactive template if codegen didn't produce one.

    Concurrency: the Frontend/Backend/DevOps agents write in parallel. Only the
    Frontend agent owns `index.html`, so the others pass `ensure_index=False` to
    avoid racing in a premature fallback page.
    """
    app_dir = APPS_ROOT / _slug(project.name)
    app_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        if not content:
            continue
        dest = app_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
    if ensure_index:
        index = app_dir / "index.html"
        if not index.exists() or "<" not in index.read_text(encoding="utf-8", errors="ignore"):
            index.write_text(working_app_html(project), encoding="utf-8")
    return app_dir


def working_app_html(project) -> str:
    """A self-contained, genuinely interactive single-file app (no build step).

    Login (any credentials) -> create/list/track records (persisted in
    localStorage) with an optional Leaflet map -> admin dashboard with stats.
    Adapts to map-based apps when the description mentions a map/location.
    """
    arch = project.architecture or {}
    name = project.name
    desc = project.description
    use_map = any(
        kw in (desc + " " + _as_text(arch.get("frontend", ""))).lower()
        for kw in ("map", "location", "geo", "pothole", "track", "delivery")
    )
    cfg = json.dumps(
        {
            "name": name,
            "desc": desc,
            "useMap": use_map,
            "stack": {k: _as_text(arch.get(k)) for k in ("frontend", "backend", "database", "deployment")},
        }
    )

    leaflet = (
        '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>'
        '<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>'
        if use_map
        else ""
    )

    return r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>__NAME__</title>
__LEAFLET__
<style>
  :root{color-scheme:dark}
  *{box-sizing:border-box}
  body{margin:0;font-family:'Segoe UI',system-ui,sans-serif;background:#0b0f17;color:#e6edf3}
  header{display:flex;align-items:center;justify-content:space-between;padding:14px 22px;background:#0f1622;border-bottom:1px solid #1f2a3a;position:sticky;top:0;z-index:500}
  header .brand{font-weight:700;font-size:18px}
  header .brand small{display:block;color:#79c0ff;font-weight:400;font-size:11px}
  nav button{background:none;border:none;color:#9aa7b4;font-size:14px;padding:8px 12px;cursor:pointer;border-radius:8px}
  nav button.active,nav button:hover{color:#fff;background:#16324f}
  .wrap{max-width:980px;margin:0 auto;padding:24px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}
  .card{background:#0f1622;border:1px solid #1f2a3a;border-radius:14px;padding:20px;margin-bottom:20px}
  h2{font-size:16px;margin:0 0 14px;color:#c9d6e4}
  label{display:block;font-size:12px;color:#9aa7b4;margin:10px 0 4px}
  input,textarea,select{width:100%;padding:10px;border-radius:8px;border:1px solid #25324a;background:#0b1119;color:#e6edf3;font-size:14px}
  button.primary{margin-top:14px;background:#2f81f7;color:#fff;border:none;padding:11px 16px;border-radius:9px;font-size:14px;cursor:pointer;font-weight:600}
  button.primary:hover{background:#4b95ff}
  .rec{border:1px solid #1f2a3a;border-radius:10px;padding:12px;margin-top:10px}
  .rec .t{font-weight:600}
  .rec .m{color:#9aa7b4;font-size:12px;margin-top:4px}
  .pill{display:inline-block;font-size:11px;padding:2px 8px;border-radius:999px;margin-top:6px}
  .New{background:#3a2a10;color:#f0b95b}.InProgress{background:#10283a;color:#5bb8f0}.Resolved{background:#0f1a12;color:#3fb950}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th,td{text-align:left;padding:8px;border-bottom:1px solid #1a2433}
  .stat{display:flex;gap:14px}.stat .box{flex:1;background:#0b1119;border:1px solid #1f2a3a;border-radius:10px;padding:14px;text-align:center}
  .stat .n{font-size:26px;font-weight:700}.stat .l{font-size:11px;color:#9aa7b4}
  #map{height:260px;border-radius:10px;margin-top:8px}
  .center{min-height:100vh;display:flex;align-items:center;justify-content:center}
  .login{width:340px}
  .muted{color:#5b6b7b;font-size:12px;text-align:center;margin-top:18px}
  .hidden{display:none}
</style>
</head>
<body>
<div id="app"></div>
<script>
const CFG = __CFG__;
const KEY = 'aifoundry_' + CFG.name.replace(/\W+/g,'_');
const STATUSES = ['New','InProgress','Resolved'];
let map, marker, picked=null;

const load = () => JSON.parse(localStorage.getItem(KEY) || '[]');
const save = (r) => localStorage.setItem(KEY, JSON.stringify(r));
const session = () => localStorage.getItem(KEY+'_user');

function logout(){ localStorage.removeItem(KEY+'_user'); render(); }
function login(e){ e.preventDefault(); const u=document.getElementById('u').value||'demo'; localStorage.setItem(KEY+'_user',u); render(); }

let view='home';
function go(v){ view=v; render(); }

function addRecord(e){
  e.preventDefault();
  const recs=load();
  recs.unshift({id:Date.now(), title:document.getElementById('rt').value, details:document.getElementById('rd').value,
    status:'New', by:session(), at:new Date().toLocaleString(), loc:picked});
  save(recs); picked=null; go('home');
}
function advance(id){ const r=load(); const x=r.find(o=>o.id===id); if(x){ x.status=STATUSES[(STATUSES.indexOf(x.status)+1)%STATUSES.length]; save(r);} render(); }
function del(id){ save(load().filter(o=>o.id!==id)); render(); }

function shell(inner){
  return `<header>
    <div class="brand">${CFG.name}<small>Generated &amp; deployed by AI Foundry · NVIDIA Nemotron</small></div>
    <nav>
      <button class="${view==='home'?'active':''}" onclick="go('home')">Home</button>
      <button class="${view==='new'?'active':''}" onclick="go('new')">Create</button>
      <button class="${view==='admin'?'active':''}" onclick="go('admin')">Admin</button>
      <button onclick="logout()">Logout (${session()})</button>
    </nav></header><div class="wrap">${inner}</div>`;
}

function homeView(){
  const recs=load();
  const list = recs.length ? recs.map(r=>`<div class="rec"><div class="t">${esc(r.title)}</div>
    <div class="m">${esc(r.details||'')}</div>
    <div class="m">by ${esc(r.by)} · ${r.at} ${r.loc?'· 📍 '+r.loc.lat.toFixed(4)+','+r.loc.lng.toFixed(4):''}</div>
    <span class="pill ${r.status}">${r.status}</span></div>`).join('') : '<p class="m">No records yet. Click “Create”.</p>';
  return shell(`<div class="card"><h2>Records</h2>${list}</div>`);
}

function newView(){
  return shell(`<div class="card"><h2>Create a record</h2>
    <form onsubmit="addRecord(event)">
      <label>Title</label><input id="rt" required placeholder="e.g. Large pothole on Main St"/>
      <label>Details</label><textarea id="rd" rows="3" placeholder="Describe it..."></textarea>
      ${CFG.useMap?'<label>Location (click the map)</label><div id="map"></div>':''}
      <button class="primary">Submit</button>
    </form></div>`);
}

function adminView(){
  const recs=load();
  const c = s => recs.filter(r=>r.status===s).length;
  const rows = recs.map(r=>`<tr><td>${esc(r.title)}</td><td><span class="pill ${r.status}">${r.status}</span></td>
    <td>${esc(r.by)}</td><td><button onclick="advance(${r.id})">Advance</button> <button onclick="del(${r.id})">Delete</button></td></tr>`).join('');
  return shell(`<div class="stat">
      <div class="box"><div class="n">${recs.length}</div><div class="l">Total</div></div>
      <div class="box"><div class="n">${c('New')}</div><div class="l">New</div></div>
      <div class="box"><div class="n">${c('InProgress')}</div><div class="l">In Progress</div></div>
      <div class="box"><div class="n">${c('Resolved')}</div><div class="l">Resolved</div></div>
    </div>
    <div class="card" style="margin-top:20px"><h2>Admin dashboard</h2>
    <table><tr><th>Title</th><th>Status</th><th>By</th><th>Actions</th></tr>${rows||'<tr><td colspan=4 class="m">No records</td></tr>'}</table></div>`);
}

function loginView(){
  return `<div class="center"><div class="card login">
    <h2>${CFG.name}</h2><p class="m">${esc(CFG.desc)}</p>
    <form onsubmit="login(event)">
      <label>Username</label><input id="u" placeholder="any username"/>
      <label>Password</label><input type="password" placeholder="any password"/>
      <button class="primary" style="width:100%">Sign in</button>
    </form><div class="muted">Demo login — any credentials work</div></div></div>`;
}

function esc(s){ return (s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }

function render(){
  const el=document.getElementById('app');
  if(!session()){ el.innerHTML=loginView(); return; }
  el.innerHTML = view==='new'?newView() : view==='admin'?adminView() : homeView();
  if(view==='new' && CFG.useMap && window.L){
    setTimeout(()=>{ map=L.map('map').setView([20.5937,78.9629],4);
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);
      map.on('click',e=>{ picked={lat:e.latlng.lat,lng:e.latlng.lng}; if(marker)marker.remove(); marker=L.marker(e.latlng).addTo(map);});
    },50);
  }
}
render();
</script>
</body>
</html>""".replace("__NAME__", html.escape(name)).replace("__LEAFLET__", leaflet).replace("__CFG__", cfg)


def npm_install(app_dir: Path) -> bool:
    """Install node deps for a generated React project. Returns success.

    Reuses an existing node_modules (so build-gate retries and self-heals don't
    repeatedly re-download the same Vite/React toolchain).
    """
    if (app_dir / "node_modules").exists():
        return True
    if not (shutil.which("npm") or shutil.which("npm.cmd")):
        log.bind(agent="developer").warning("npm not found on PATH; cannot install node deps")
        return False
    try:
        result = subprocess.run(
            [_NPM, "install", "--no-audit", "--no-fund"],
            cwd=str(app_dir),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=300,
            shell=False,
        )
        return result.returncode == 0 and (app_dir / "node_modules").exists()
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="developer").warning("npm install failed: {}", exc)
        return False


def vite_build(app_dir: Path) -> tuple[bool, str]:
    """Run `npm run build` (Vite/Rollup) as a real compile gate.

    Returns (ok, combined_output). This is what catches JSX syntax errors,
    undefined references, bad imports, etc. BEFORE the app is ever served — the
    same signal the Frontend agent feeds back to the model to auto-fix the code.
    """
    try:
        result = subprocess.run(
            [_NPM, "run", "build"],
            cwd=str(app_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=240,
            shell=False,
        )
        output = result.stdout or ""
        ok = result.returncode == 0 and (app_dir / "dist").exists()
        return ok, output
    except subprocess.TimeoutExpired:
        return False, "vite build timed out after 240s"
    except Exception as exc:  # noqa: BLE001
        return False, f"vite build error: {exc}"


_IMPORT_CHECK = (
    "import importlib.util;"
    "spec = importlib.util.spec_from_file_location('genmain', 'main.py');"
    "m = importlib.util.module_from_spec(spec);"
    "spec.loader.exec_module(m);"
    "assert hasattr(m, 'app'), 'no FastAPI app object named `app` (uvicorn main:app needs it)'"
)


def backend_build(app_dir: Path) -> tuple[bool, str]:
    """Compile-gate the generated FastAPI backend.

    1) `py_compile` catches syntax errors / truncated files (the main risk).
    2) Best-effort import of backend/main.py with the control-plane interpreter
       catches NameErrors, bad app definitions, missing `app`, etc. A
       ModuleNotFoundError for an uninstalled third-party package is NOT treated
       as a failure (we don't pip-install the generated backend's deps here).

    Returns (ok, output).
    """
    backend_dir = app_dir / "backend"
    main = backend_dir / "main.py"
    if not main.exists():
        return False, "backend/main.py missing"

    try:
        syntax = subprocess.run(
            [sys.executable, "-m", "py_compile", str(main)],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=60, shell=False,
        )
        if syntax.returncode != 0:
            return False, "py_compile failed:\n" + (syntax.stderr or syntax.stdout or "syntax error")

        imp = subprocess.run(
            [sys.executable, "-c", _IMPORT_CHECK],
            cwd=str(backend_dir),
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=60, shell=False,
        )
        if imp.returncode != 0:
            err = (imp.stderr or imp.stdout or "").strip()
            if "ModuleNotFoundError" in err or "No module named" in err:
                # External dependency we don't install in this env — syntax is valid.
                return True, "syntax OK (import skipped: external dependency not installed)"
            return False, "import failed:\n" + err
        return True, "backend OK (py_compile + import + app present)"
    except subprocess.TimeoutExpired:
        return False, "backend build timed out"
    except Exception as exc:  # noqa: BLE001
        return False, f"backend build error: {exc}"


def start_backend(project) -> Optional[str]:
    """Start (or restart) the generated FastAPI backend with uvicorn.

    Runs `uvicorn main:app` from the project's backend/ dir using the
    control-plane interpreter (so fastapi/uvicorn/pydantic are available).
    Returns the live API URL, or None if there's no backend to run.
    """
    stop_backend(project)
    backend_dir = APPS_ROOT / _slug(project.name) / "backend"
    if not (backend_dir / "main.py").exists():
        return None
    port = _free_port()
    try:
        proc = subprocess.Popen(
            [sys.executable, "-m", "uvicorn", "main:app",
             "--host", "127.0.0.1", "--port", str(port), "--log-level", "warning"],
            cwd=str(backend_dir),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            shell=False,
        )
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="deployment").warning("could not start backend uvicorn: {}", exc)
        return None
    _RUNNING_API[project.id] = {"port": port, "proc": proc, "dir": backend_dir}
    _wait_ready(port, timeout=20)
    url = f"http://localhost:{port}/"
    log.bind(agent="deployment").info("Backend API up at {}", url)
    return url


def stop_backend(project) -> None:
    """Stop the project's live FastAPI backend if running."""
    entry = _RUNNING_API.pop(project.id, None)
    if not entry:
        return
    _kill_proc(entry["proc"])
    log.bind(agent="deployment").info("Backend API stopped (port {})", entry["port"])


def current_api_url(project) -> Optional[str]:
    entry = _RUNNING_API.get(project.id)
    return f"http://localhost:{entry['port']}/" if entry else None


def _inject_api_base(app_dir: Path, api_url: str) -> None:
    """Make the live backend reachable from the browser by setting
    window.API_BASE in the served index.html (runs before the React bundle)."""
    idx = app_dir / "index.html"
    if not idx.exists():
        return
    try:
        text = idx.read_text(encoding="utf-8", errors="ignore")
        text = re.sub(r"<script>window\.API_BASE=.*?</script>\s*", "", text, flags=re.DOTALL)
        snippet = f"<script>window.API_BASE={json.dumps(api_url.rstrip('/'))};</script>"
        if "<head>" in text:
            text = text.replace("<head>", "<head>\n    " + snippet, 1)
        else:
            text = snippet + "\n" + text
        idx.write_text(text, encoding="utf-8")
    except Exception as exc:  # noqa: BLE001
        log.bind(agent="deployment").warning("could not inject API_BASE: {}", exc)


def start(project) -> str:
    """Start (or restart) the project's local servers. Returns the frontend URL.

    Brings up the generated FastAPI backend first (so its URL can be injected as
    window.API_BASE), then serves the frontend: React/Vite projects via the Vite
    dev server; plain static bundles via http.server.
    """
    stop(project)
    app_dir = APPS_ROOT / _slug(project.name)

    # Live backend first, so the frontend can be pointed at it.
    api_url = start_backend(project)
    if api_url:
        _inject_api_base(app_dir, api_url)

    port = _free_port()

    is_node = (app_dir / "package.json").exists() and (app_dir / "node_modules").exists()
    if is_node:
        proc = subprocess.Popen(
            [_NPM, "run", "dev", "--", "--port", str(port), "--strictPort",
             "--host", "127.0.0.1"],
            cwd=str(app_dir),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            shell=False,
        )
        _RUNNING[project.id] = {"port": port, "proc": proc, "dir": app_dir, "kind": "node"}
        _wait_ready(port, timeout=30)
        url = f"http://localhost:{port}/"
        log.bind(agent="deployment").info("Vite dev server up at {}", url)
        return url

    if not (app_dir / "index.html").exists():
        build_app(project)
    proc = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(port), "--bind", "127.0.0.1",
         "--directory", str(app_dir)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    _RUNNING[project.id] = {"port": port, "proc": proc, "dir": app_dir, "kind": "static"}
    _wait_ready(port, timeout=10)
    url = f"http://localhost:{port}/"
    log.bind(agent="deployment").info("Local app server up at {}", url)
    return url


def _wait_ready(port: int, timeout: int = 20) -> bool:
    """Block until the port accepts TCP connections (server is up)."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=1):
                return True
        except OSError:
            time.sleep(0.4)
    return False


def _kill_proc(proc) -> None:
    """Kill a child process and its tree (npm/vite/uvicorn spawn children)."""
    try:
        if proc.poll() is not None:
            return
        if sys.platform.startswith("win"):
            subprocess.run(
                ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
        else:
            proc.terminate()
            proc.wait(timeout=5)
    except Exception:  # noqa: BLE001
        try:
            proc.kill()
        except Exception:  # noqa: BLE001
            pass


def stop(project) -> None:
    """Stop the project's local servers (frontend + backend) if running."""
    stop_backend(project)
    entry = _RUNNING.pop(project.id, None)
    if not entry:
        return
    _kill_proc(entry["proc"])
    log.bind(agent="monitoring").warning("App server stopped (port {})", entry["port"])


def current_url(project) -> Optional[str]:
    entry = _RUNNING.get(project.id)
    return f"http://localhost:{entry['port']}/" if entry else None
   