general:
  front_end:
    _type: fastapi

llms:
  nemotron:
    _type: nim
    model_name: nvidia/llama-3.3-nemotron-super-49b-v1.5
    temperature: 0.3
    max_tokens: 700

workflow:
  _type: langgraph_wrapper
  dependencies:
    - ./nat_foundry/langgraph_agent
  graph: nat_foundry/langgraph_agent/architect_graph.py:graph
  env: .env
